### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
from functools import reduce

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data_df = pd.read_csv(file_to_load)

In [2]:
# Show just the header
purchase_data_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [3]:
# Get a Series object containing the data type objects of each column of Dataframe.
# Index of series is column name.
dataTypeSeries = purchase_data_df.dtypes

print('Data type of each column of Dataframe :')
dataTypeSeries

Data type of each column of Dataframe :

Purchase ID      int64
SN              object
Age              int64
Gender          object
Item ID          int64
Item Name       object
Price          float64
dtype: object

In [4]:
# Identify incomplete rows
purchase_data_df.count()

Purchase ID    780
SN             780
Age            780
Gender         780
Item ID        780
Item Name      780
Price          780
dtype: int64

In [5]:
# Count unique values for certain variables

unique_players_df = purchase_data_df[["SN"]].drop_duplicates().count()

unique_products_df = purchase_data_df[["Item ID"]].drop_duplicates().count()

unique_sales_df = purchase_data_df[["Purchase ID"]].drop_duplicates().count()

print(unique_players_df)
print(unique_products_df)
print(unique_sales_df)

SN    576
dtype: int64
Item ID    179
dtype: int64
Purchase ID    780
dtype: int64

In [6]:
# The information in the two cells above helps us to know the following:
#     1. Each sale involves only one item in inventory (aka product).
#     2. 204 sales were to existing customers.  (780 total sales less - 576 total unique customers)
#     3. Without yet zoing in on which products were most popular, a product base of 179 products 
#        available for sale accounted for 780 total sales during whatever period has produced the 
#        data set as provided.

In [7]:
# Display a statistical overview of the DataFrame
purchase_data_df.describe()

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   91.755128    3.050987
std     225.310896    6.659444   52.697702    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   47.750000    1.980000
50%     389.500000   22.000000   92.000000    3.150000
75%     584.250000   25.000000  138.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

## Player Count

* Display the total number of players

In [8]:
# Display the total number of players
players = len(purchase_data_df["SN"].unique())
print(f"Total Players = {players}")

# I realize this is redundant with an earlier exercise, but since this was explicitly directed for as part 
#     of the Case homework assignment, I am providing it in stand-alone fashion so as not to be overlooked.

Total Players = 576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [9]:
# Create logic to calculate 
#     number of items purchased, 
#     average price for items actually purchased,
#     number of purchases, and
#     total revenue

items = len(purchase_data_df["Item ID"].unique())
avg_price = purchase_data_df["Price"].mean()
purchases = len(purchase_data_df["Purchase ID"])
total = purchase_data_df["Price"].sum()

# Test print the items that will go into the summary data frame
print(f"Unique Items = {items}")
print(f"Average Price = ${avg_price:,.2f}")
print(f"Purchases = {purchases}")
print(f"Total Revenue = ${total:,.2f}")

Unique Items = 179
Average Price = $3.05
Purchases = 780
Total Revenue = $2,379.77

In [10]:
# Create a DataFrame of elements analyzed using a list of dictionaries, in this case a single dictionary
analysis_list = [
    {"Unique Items": items, "Average Price": avg_price, "Purchases": purchases, "Total Revenue": total},
]
analysis_df = pd.DataFrame(analysis_list)

# Format currency
analysis_df.style.format({"Average Price": "${:,.2f}", "Total Revenue": "${:,.2f}"})

# analysis_df

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [11]:
# Create dataframe of SN and Gender
gender_df = purchase_data_df[["SN", "Gender"]].drop_duplicates()
gender_df

                SN  Gender
0          Lisim78    Male
1      Lisovynya38    Male
2       Ithergue48    Male
3    Chamassasya86    Male
4        Iskosia90    Male
..             ...     ...
773         Hala31    Male
774     Jiskjask80    Male
775     Aethedru70  Female
777     Yathecal72    Male
778        Sisur91    Male

[576 rows x 2 columns]

In [12]:
# Number of unique individuals by gender
gender_counts = gender_df["Gender"].value_counts()

# Convert Gender Counts from value_count() to DataFrame
gender_counts_cvt = pd.DataFrame(gender_counts)
gender_counts_cvt_df = gender_counts_cvt.reset_index()
gender_counts_cvt_df.columns = ["Gender", "Total Count"] # change column names
gender_counts_cvt_df

                  Gender  Total Count
0                   Male          484
1                 Female           81
2  Other / Non-Disclosed           11

In [13]:
# Percentage of unique individuals by gender
gender_percent = gender_df["Gender"].value_counts(normalize=True).mul(100).round(1).astype(str) + "%"

# Convert Gender Percentage from value_count() to DataFrame
gender_percent_cvt = pd.DataFrame(gender_percent)
gender_percent_cvt_df = gender_percent_cvt.reset_index()
gender_percent_cvt_df.columns = ["Gender", "Percentage"] # change column names
gender_percent_cvt_df

                  Gender Percentage
0                   Male      84.0%
1                 Female      14.1%
2  Other / Non-Disclosed       1.9%

In [14]:
# Merge two dataframes using an inner join
gender_merge_df = pd.merge(gender_counts_cvt_df, gender_percent_cvt_df, on="Gender")
gender_merge_df

                  Gender  Total Count Percentage
0                   Male          484      84.0%
1                 Female           81      14.1%
2  Other / Non-Disclosed           11       1.9%


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [15]:
# Extract the following columns: "Gender", "Price""
purchase_gender_df = purchase_data_df[["Gender", "Price"]]
purchase_gender_df.head()

  Gender  Price
0   Male   3.53
1   Male   1.56
2   Male   4.88
3   Male   3.27
4   Male   1.44

In [16]:
# Create a dataframe of Purchase Count by Gender
gender_group = purchase_gender_df.groupby(["Gender"])
gender_purchase_count_df = gender_group.count()

# Convert 2nd column title from Price to Purchase Count
gender_purchase_count_cvt_df = gender_purchase_count_df.reset_index()
gender_purchase_count_cvt_df.columns = ["Gender", "Purchase Count"] # change column names
gender_purchase_count_cvt_df

                  Gender  Purchase Count
0                 Female             113
1                   Male             652
2  Other / Non-Disclosed              15

In [17]:
# Create a dataframe of Average Purchase Price by Gender
gender_purchase_avg_price_df = gender_group.mean()

# Convert 2nd column title from Price to Average Purchase Price
gender_purchase_avg_price_cvt_df = gender_purchase_avg_price_df.reset_index()
gender_purchase_avg_price_cvt_df.columns = ["Gender", "Average Purchase Price"] # change column names

gender_purchase_avg_price_cvt_df

                  Gender  Average Purchase Price
0                 Female                3.203009
1                   Male                3.017853
2  Other / Non-Disclosed                3.346000

In [18]:
# Create a dataframe of Total Purchase Value by Gender
gender_purchase_total_df = gender_group.sum()

# Convert 2nd column title from Price to Average Purchase Price
gender_purchase_total_cvt_df = gender_purchase_total_df.reset_index()
gender_purchase_total_cvt_df.columns = ["Gender", "Total Purchase Value"] # change column names

gender_purchase_total_cvt_df

                  Gender  Total Purchase Value
0                 Female                361.94
1                   Male               1967.64
2  Other / Non-Disclosed                 50.19

In [19]:
# Compile the list of dataframes you want to merge
data_frames = [gender_counts_cvt_df, 
    gender_purchase_count_cvt_df, 
    gender_purchase_avg_price_cvt_df, 
    gender_purchase_total_cvt_df]

# Merging list of dataframes
gender_merge_2_df = reduce(lambda  left,right: pd.merge(left,right,on=["Gender"], how='outer'), data_frames)
gender_merge_2_df

,Gender,Total Count,Purchase Count,Average Purchase Price,Total Purchase Value
0,Male,484,652,3.017853,1967.64
1,Female,81,113,3.203009,361.94
2,Other / Non-Disclosed,11,15,3.346000,50.19

In [20]:
# Calculate the Avg Purchase Value per Person by Gender
gender_avg_purchase_val_df = gender_merge_2_df["Total Purchase Value"]/gender_merge_2_df["Total Count"]
gender_avg_purchase_val_df

0    4.065372
1    4.468395
2    4.562727
dtype: float64

In [21]:
# Use DataFrame.insert() to add a column 
gender_merge_2_df.insert(4, "Avg Purchase Value per Person", gender_avg_purchase_val_df, True)
gender_merge_2_df

,Gender,Total Count,Purchase Count,Average Purchase Price,Avg Purchase Value per Person,Total Purchase Value
0,Male,484,652,3.017853,4.065372,1967.64
1,Female,81,113,3.203009,4.468395,361.94
2,Other / Non-Disclosed,11,15,3.346000,4.562727,50.19

In [22]:
# Add formatting for (1) percentage, (2) currency formatting, and (3) decimals, as appropriate
# Employed a dictionary method
gender_format_dict = {"Average Purchase Price": "${:,.2f}", 
                        "Avg Purchase Value per Person": "${:,.2f}", 
                        "Total Purchase Value": "${:,.2f}"} 

gender_merge_2_df.style.format(gender_format_dict).hide_index()

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [23]:
# Copy master dataframe data to new dataframe for age analytics
age_df = purchase_data_df

In [24]:
# Create bins in which to place values based upon TED Talk views
bins = [0, 9.99999, 14.99999, 19.99999, 24.99999, 29.99999,34.99999, 39.99999, 999.99999]

# Create labels for these bins
group_labels = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [25]:
# Slice the data and place it into bins
# Create a new dataframe for this sliced data
pd.cut(age_df["Age"], bins, labels=group_labels).head()

0    20-24
1      40+
2    20-24
3    20-24
4    20-24
Name: Age, dtype: category
Categories (8, object): [<10 < 10-14 < 15-19 < 20-24 < 25-29 < 30-34 < 35-39 < 40+]

In [26]:
# Place the data series into a new column inside of the DataFrame with column header Age Group
age_df["Age Group"] = pd.cut(age_df["Age"], bins, labels=group_labels)
age_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24

In [27]:
# Create new DataFrame based on unique players
# It is a subset of the DataFrame age_df
unique_SN_age_df = age_df.drop_duplicates(subset=["SN"], keep="first")

In [28]:
# Create a GroupBy object based upon "View Group"
unique_SN_age_group = unique_SN_age_df.groupby("Age Group")

# Number of unique individuals by age category (bin)
age_group_counts = unique_SN_age_group["SN"].count()

# Convert Age Group Counts from value_count() to DataFrame
age_group_counts_cvt = pd.DataFrame(age_group_counts)
age_group_counts_cvt_df = age_group_counts_cvt.reset_index()
age_group_counts_cvt_df.columns = ["Age Group", "Total Count"] # change column names
age_group_counts_cvt_df

  Age Group  Total Count
0       <10           17
1     10-14           22
2     15-19          107
3     20-24          258
4     25-29           77
5     30-34           52
6     35-39           31
7       40+           12

In [29]:
# Calculate total number of unique players
total_age_group = np.sum(age_group_counts_cvt_df["Total Count"].values)
total_age_group

576

In [30]:
# Add column Percentage to DataFrame of unique players
age_group_counts_cvt_df["Percentage"] = age_group_counts_cvt_df["Total Count"]/total_age_group
age_group_counts_cvt_df

  Age Group  Total Count  Percentage
0       <10           17    0.029514
1     10-14           22    0.038194
2     15-19          107    0.185764
3     20-24          258    0.447917
4     25-29           77    0.133681
5     30-34           52    0.090278
6     35-39           31    0.053819
7       40+           12    0.020833

In [31]:
# Add formatting for (1) percentage, (2) currency formatting, and (3) decimals, as appropriate
# Employed a dictionary method
age_group_format_dict = {"Percentage": "{:.1%}"} 

age_group_counts_cvt_df.style.format(age_group_format_dict).hide_index()

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [32]:
# Extract the following columns: "Age", "Price"" into a new working DataFrame
purchase_age_df = age_df[["Age Group", "Price"]]
purchase_age_df.head()

  Age Group  Price
0     20-24   3.53
1       40+   1.56
2     20-24   4.88
3     20-24   3.27
4     20-24   1.44

In [33]:
# Create a dataframe of Purchase Count by Age Group
purchase_age_group = purchase_age_df.groupby(["Age Group"])
age_group_purchase_count_df = purchase_age_group.count()

# Convert 2nd column title from Price to Average Purchase Price
age_group_purchase_count_cvt_df = age_group_purchase_count_df.reset_index()
age_group_purchase_count_cvt_df.columns = ["Age Group", "Purchase Count"] # change column names

age_group_purchase_count_cvt_df

  Age Group  Purchase Count
0       <10              23
1     10-14              28
2     15-19             136
3     20-24             365
4     25-29             101
5     30-34              73
6     35-39              41
7       40+              13

In [34]:
# Create a dataframe of Average Purchase Price by Age Group
age_group_avg_purchase_price_df = purchase_age_group.mean()

# Convert 2nd column title from Price to Average Purchase Price
age_group_avg_purchase_price_cvt_df = age_group_avg_purchase_price_df.reset_index()
age_group_avg_purchase_price_cvt_df.columns = ["Age Group", "Average Purchase Price"] # change column names

age_group_avg_purchase_price_cvt_df

  Age Group  Average Purchase Price
0       <10                3.353478
1     10-14                2.956429
2     15-19                3.035956
3     20-24                3.052219
4     25-29                2.900990
5     30-34                2.931507
6     35-39                3.601707
7       40+                2.941538

In [35]:
# Create a dataframe of Total Purchase Value by Age Group
age_purchase_value_df = purchase_age_group.sum()

# Convert 2nd column title from Price to Average Purchase Price
age_purchase_value_cvt_df = age_purchase_value_df.reset_index()
age_purchase_value_cvt_df.columns = ["Age Group", "Total Purchase Value"] # change column names

age_purchase_value_cvt_df

  Age Group  Total Purchase Value
0       <10                 77.13
1     10-14                 82.78
2     15-19                412.89
3     20-24               1114.06
4     25-29                293.00
5     30-34                214.00
6     35-39                147.67
7       40+                 38.24

In [36]:
# Compile the list of dataframes you want to merge
data_frames_2 = [age_group_counts_cvt_df, 
    age_group_purchase_count_cvt_df, 
    age_group_avg_purchase_price_cvt_df, 
    age_purchase_value_cvt_df]

# Merging list of dataframes
age_group_merge_df = reduce(lambda  left,right: pd.merge(left,right,on=["Age Group"], how='outer'), data_frames_2)
age_group_merge_df

,Age Group,Total Count,Percentage,Purchase Count,Average Purchase Price,Total Purchase Value
0,<10,17,0.029514,23,3.353478,77.13
1,10-14,22,0.038194,28,2.956429,82.78
2,15-19,107,0.185764,136,3.035956,412.89
3,20-24,258,0.447917,365,3.052219,1114.06
4,25-29,77,0.133681,101,2.900990,293.00
5,30-34,52,0.090278,73,2.931507,214.00
6,35-39,31,0.053819,41,3.601707,147.67
7,40+,12,0.020833,13,2.941538,38.24

In [37]:
# Calculate the Avg Purchase Value per Person by Age Group
age_group_avg_purchase_val_df = age_group_merge_df["Total Purchase Value"]/age_group_merge_df["Total Count"]
age_group_avg_purchase_val_df

0    4.537059
1    3.762727
2    3.858785
3    4.318062
4    3.805195
5    4.115385
6    4.763548
7    3.186667
dtype: float64

In [38]:
# Add column Average Purchase Value per Person to summary data by age group DataFrame 
age_group_merge_df["Avg Purchase Value per Person"] = age_group_merge_df["Total Purchase Value"]/age_group_merge_df["Total Count"]

age_group_merge_df

,Age Group,Total Count,Percentage,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Purchase Value per Person
0,<10,17,0.029514,23,3.353478,77.13,4.537059
1,10-14,22,0.038194,28,2.956429,82.78,3.762727
2,15-19,107,0.185764,136,3.035956,412.89,3.858785
3,20-24,258,0.447917,365,3.052219,1114.06,4.318062
4,25-29,77,0.133681,101,2.900990,293.00,3.805195
5,30-34,52,0.090278,73,2.931507,214.00,4.115385
6,35-39,31,0.053819,41,3.601707,147.67,4.763548
7,40+,12,0.020833,13,2.941538,38.24,3.186667

In [39]:
# Add formatting for (1) percentage, (2) currency formatting, and (3) decimals, as appropriate
# Employed a dictionary method
age_group_format_dict_2 = {"Average Purchase Price": "${:,.2f}", 
                        "Avg Purchase Value per Person": "${:,.2f}", 
                        "Total Purchase Value": "${:,.2f}",
                        "Percentage": "{:.1%}"} 

age_group_merge_df.style.format(age_group_format_dict_2).hide_index()

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [40]:
# Create dataframe of SN and Price (purchase price for any individual item sold)
top_spenders_df = purchase_data_df[["SN", "Purchase ID", "Price", "Age"]]
top_spenders_df.head()

              SN  Purchase ID  Price  Age
0        Lisim78            0   3.53   20
1    Lisovynya38            1   1.56   40
2     Ithergue48            2   4.88   24
3  Chamassasya86            3   3.27   24
4      Iskosia90            4   1.44   23

In [51]:
# Create a dataframe of Purchase Count by Top Spender
top_spenders_group = top_spenders_df.groupby(["SN"])
top_spenders_purchase_count_df = top_spenders_group[["Purchase ID"]].count()

# Rename column heading
top_spenders_purchase_count_cvt = pd.DataFrame(top_spenders_purchase_count_df)
top_spenders_purchase_count_cvt_df = top_spenders_purchase_count_cvt.reset_index()
top_spenders_purchase_count_cvt_df.columns = ["SN", "Purchase Count"] # change column names
top_spenders_purchase_count_cvt_df

                SN  Purchase Count
0     Adairialis76               1
1      Adastirin33               1
2           Aeda94               1
3           Aela59               1
4        Aelaria33               1
..             ...             ...
571     Yathecal82               3
572     Yathedeu43               2
573  Yoishirrala98               1
574     Zhisrisu83               2
575      Zontibe81               3

[576 rows x 2 columns]

In [49]:
# Create a dataframe of Average Purchase Price by Top Spender
top_spenders_avg_purchase_price_df = top_spenders_group[["Price"]].mean()

# Rename column heading
top_spenders_avg_purchase_price_cvt = pd.DataFrame(top_spenders_avg_purchase_price_df)
top_spenders_avg_purchase_price_cvt_df = top_spenders_avg_purchase_price_cvt.reset_index()
top_spenders_avg_purchase_price_cvt_df.columns = ["SN", "Average Purchase Price"] # change column names
top_spenders_avg_purchase_price_cvt_df

                SN  Average Purchase Price
0     Adairialis76                2.280000
1      Adastirin33                4.480000
2           Aeda94                4.910000
3           Aela59                4.320000
4        Aelaria33                1.790000
..             ...                     ...
571     Yathecal82                2.073333
572     Yathedeu43                3.010000
573  Yoishirrala98                4.580000
574     Zhisrisu83                3.945000
575      Zontibe81                2.676667

[576 rows x 2 columns]

In [50]:
# Create a dataframe of Total Purchase Value by Top Spender
top_spenders_purchase_value_df = top_spenders_group[["Price"]].sum()

# Rename column heading
top_spenders_purchase_value_cvt = pd.DataFrame(top_spenders_purchase_value_df)
top_spenders_purchase_value_cvt_df = top_spenders_purchase_value_cvt.reset_index()
top_spenders_purchase_value_cvt_df.columns = ["SN", "Total Purchase Value"] # change column names
top_spenders_purchase_value_cvt_df

                SN  Total Purchase Value
0     Adairialis76                  2.28
1      Adastirin33                  4.48
2           Aeda94                  4.91
3           Aela59                  4.32
4        Aelaria33                  1.79
..             ...                   ...
571     Yathecal82                  6.22
572     Yathedeu43                  6.02
573  Yoishirrala98                  4.58
574     Zhisrisu83                  7.89
575      Zontibe81                  8.03

[576 rows x 2 columns]

In [53]:
# Compile the list of dataframes you want to merge
data_frames_3 = [top_spenders_purchase_count_cvt_df, 
    top_spenders_avg_purchase_price_cvt_df, 
    top_spenders_purchase_value_cvt_df]

# Merging list of dataframes
top_spenders_merge_df = reduce(lambda  left,right: pd.merge(left,right,on=["SN"], how='outer'), data_frames_3)
top_spenders_merge_df.head()

             SN  Purchase Count  Average Purchase Price  Total Purchase Value
0  Adairialis76               1                    2.28                  2.28
1   Adastirin33               1                    4.48                  4.48
2        Aeda94               1                    4.91                  4.91
3        Aela59               1                    4.32                  4.32
4     Aelaria33               1                    1.79                  1.79

In [58]:
# To sort from highest to lowest, ascending=False must be passed in
top_spenders_merge_srt_df = top_spenders_merge_df.sort_values("Total Purchase Value", ascending=False)
top_spenders_merge_srt_df.head()

              SN  Purchase Count  Average Purchase Price  Total Purchase Value
360    Lisosia93               5                3.792000                 18.96
246  Idastidru52               4                3.862500                 15.45
106   Chamjask73               3                4.610000                 13.83
275       Iral74               4                3.405000                 13.62
281  Iskadarya95               3                4.366667                 13.10

In [64]:
# Add formatting for (1) percentage, (2) currency formatting, and (3) decimals, as appropriate
# Employed a dictionary method
top_spenders_format_dict = {"Average Purchase Price": "${:,.2f}", 
                        "Total Purchase Value": "${:,.2f}"} 

top_spenders_final_df = top_spenders_merge_srt_df.style.format(top_spenders_format_dict).hide_index()
top_spenders_final_df

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, average item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame